#! /usr/bin/env python

# standard imports
from matplotlib import pyplot as plt
import pandas as pd
import sys
import os
import argparse
import logging
import argparse

# synchrofit
from SynchrofitTool.synchrofit import spectral_fitter, spectral_data, spectral_plotter, spectral_ages, spectral_units, logger, color_text, Colors

__author__ = 'Benjamin Quici'

# command line version of this program runs from here.
if __name__ == "__main__":
    parser = argparse.ArgumentParser(prefix_chars='-')
    group1 = parser.add_argument_group('Configuration Options')
    group1.add_argument("--data", dest='data', type=str, 
                        help='(No default) Name of the data file containing the input spectrum (requires .dat extension)')
    group1.add_argument('--work_dir', dest='work_dir', type=str, default=None, 
                        help='(Default = None) Directory to which fitting outputs and plots are written to. If None, defaults to current working directory.')
    group1.add_argument("--freq", dest='freq', type=float, nargs='+', default=None, 
                        help='(Default = None) List of input frequencies (if --data is not specified).')
    group1.add_argument("--flux", dest='flux', type=float, nargs='+', default=None, 
                        help='(Default = None) List of input flux densities (if --data is not specified)')
    group1.add_argument("--err_flux", dest='err_flux', type=float, nargs='+', default=None, 
                        help='(Default = None) List of input flux density errors (if --data is not specified)')
    group1.add_argument("--freq_unit", dest='freq_unit', type=str, default='Hz', 
                        help='(Default = None) Input frequency units')
    group1.add_argument("--flux_unit", dest='flux_unit', type=str, default='Jy', 
                        help='(Default = None) Input flux density units')
    
    group2 = parser.add_argument_group('Fitting Options')
    group2.add_argument("--fit_type", dest='fit_type', type=str, default=None, 
                        help='(No default) Model to fit: JP, KP, CI')
    group2.add_argument("--n_breaks", dest='n_breaks', type=int, default=31, 
                        help='(Default = 31) Number of increments with which to sample the break frequency range')
    group2.add_argument("--n_injects", dest='n_injects', type=int, default=31, 
                        help='(Default = 31) Number of increments with which to sample the injection index range')
    group2.add_argument("--n_remnants", dest='n_remnants', type=int, default=31, 
                        help='(Default = 31) Number of increments with which to sample the remnant ratio range')
    group2.add_argument("--n_iterations", dest='n_iterations', type=int, default=3, 
                        help='(Default = 3) Number of iterations.')
    group2.add_argument("--break_range", dest='break_range', type=float, nargs='+', default=[8, 11], 
                        help='(Default = [8, 11]) Accepted range for the log(break frequency) in Hz')
    group2.add_argument("--inject_range", dest='inject_range', type=float, nargs='+', default=[2.01, 2.99], 
                        help='(Default = [2.01, 2.99]) Accepted range for the energy injection index')
    group2.add_argument("--remnant_range", dest='remnant_range', type=float, nargs='+', default=[0, 1], 
                        help='(Default = [0, 1]) Accepted range for the remnant ratio')

    group3 = parser.add_argument_group('Output Model Options')
    group3.add_argument("--n_model_freqs", dest='n_model_freqs', type=int, default=100, 
                        help='(Default = 100) Number of frequencies to evaluate the model at')
    group3.add_argument("--mc_length", dest='mc_length', type=int, default=500, 
                        help='(Default = 500) Number of Monte-Carlo iterations used to estimate the model uncertainty')
    group3.add_argument("--err_model_width", dest='err_model_width', type=int, default=2, 
                        help='(Default = 2) Width of the uncertainty envelope on the model, in units of sigma')

    group4 = parser.add_argument_group('Extra fitting options')
    group4.add_argument('--plot', dest='plot', action='store_true',default=False, 
                        help='(Default = False) If True, produce a plot of the observed spectrum and fitted model')
    group4.add_argument('--write_model', dest='write_model', action='store_true', default=False, 
                        help='(Default = False) If True, write the fitting outputs to file')

    group5 = parser.add_argument_group('Spectral age options')
    group5.add_argument('--age', dest='age', action='store_true', default=False, 
                        help='(Default = False) If True, determine the spectral age of the source (requires --bfield and --z)')
    group5.add_argument('--bfield', dest='bfield', type=float, default=None, 
                        help='(No default) Magnetic field strength in units of nT')
    group5.add_argument('--z', dest='z', type=float, default=None, 
                        help='(No default) Cosmological redshift of the source')
    options = parser.parse_args()

    if options.data == None and options.freq == None:
        parser.print_help()
        print(color_text('No input data given.', c=Colors.Red))
        sys.exit(1)

    colorstring = color_text("Reading in data", Colors.Orange)
    print("INFO __main__ {}".format(colorstring))
    if options.data:
        if options.work_dir is not None:
            filename = '{}/{}'.format(options.work_dir, options.data)
        else:
            filename = '{}'.format(options.data)
        df_data = pd.read_csv(filename)
        frequency = spectral_units(df_data.iloc[:,1].values, options.freq_unit)
        luminosity = spectral_units(df_data.iloc[:,2].values, options.flux_unit)
        dluminosity = spectral_units(df_data.iloc[:,3].values, options.flux_unit)
    elif options.freq:
        frequency = spectral_units(np.asarray(options.freq), options.freq_unit)
        luminosity = spectral_units(np.asarray(options.flux), options.flux_unit)
        dluminosity = spectral_units(np.asarray(options.err_flux), options.flux_unit)
    
    espace='            '
    colorstring = color_text("Estimating free parameters.", Colors.Orange)
    print("INFO __main__ {}".format(colorstring))
    params = spectral_fitter(frequency, luminosity, dluminosity, options.fit_type, options=options)
    
    colorstring = color_text("Evaluating model and estimating model uncertainties.", Colors.Orange)
    print("INFO __main__ {}".format(colorstring))
    frequency_model, luminosity_model, err_luminosity_model, luminosity_model_min, luminosity_model_max = spectral_data(frequency, params, work_dir=options.work_dir, write_model=options.write_model)
    
    if options.plot:
        colorstring = color_text("Writing model fit to figure", Colors.Orange)
        print("INFO __main__ {}".format(colorstring))
        spectral_plotter(frequency, luminosity, dluminosity, frequency_model, luminosity_model, err_luminosity_model, luminosity_model_min, luminosity_model_max, options.work_dir, options.fit_type, options.err_model_width)
    
    if options.age:
        colorstring = color_text("Estimating spectral ages", Colors.Orange)
        print("INFO __main__ {}".format(colorstring))
        params = (params[0], 10**params[1], params[5])
        spectral_ages(params, options.bfield, options.z)
